--------------------------------------------------------
--  File created - Monday-September-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT_GRADE
--------------------------------------------------------

  CREATE TABLE "KRIS"."STUDENT_GRADE" 
   (	"STUDENT_ID" VARCHAR2(250 BYTE), 
	"STUDENT_FIRSTNAME" VARCHAR2(250 BYTE), 
	"STUDENT_LASTNAME" VARCHAR2(250 BYTE), 
	"STUDENT_COURSENAME" VARCHAR2(250 BYTE), 
	"STUDENT_SCORE" NUMBER, 
	"LETTER_GRADE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KRIS.STUDENT_GRADE
SET DEFINE OFF;
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0001','Jack','Tester','Programming',85,'A-');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0001','Jack','Tester','Math',94,'A');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0001','Jack','Tester','English',77,'B');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0001','Jack','Tester','Physics',67,'C+');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0002','Mike','Allston','Programming',58,'C-');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0002','Mike','Allston','Math',44,'D-');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0002','Mike','Allston','English',37,'F');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0002','Mike','Allston','Physics',49,'D');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0003','Nicholas','Sanders','Programming',54,'D+');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0003','Nicholas','Sanders','Math',62,'C');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0003','Nicholas','Sanders','English',97,'A+');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0003','Nicholas','Sanders','Physics',81,'B+');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0004','Christopher','Ingram','Programming',71,'B-');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0004','Christopher','Ingram','Math',53,'D+');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0004','Christopher','Ingram','English',47,'D');
Insert into KRIS.STUDENT_GRADE (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,STUDENT_COURSENAME,STUDENT_SCORE,LETTER_GRADE) values ('S0004','Christopher','Ingram','Physics',27,'F');
--------------------------------------------------------
--  DDL for Index STUDENT_GRADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KRIS"."STUDENT_GRADE_PK" ON "KRIS"."STUDENT_GRADE" ("STUDENT_ID", "STUDENT_COURSENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENT_GRADE
--------------------------------------------------------

  ALTER TABLE "KRIS"."STUDENT_GRADE" ADD CONSTRAINT "STUDENT_GRADE_PK" PRIMARY KEY ("STUDENT_ID", "STUDENT_COURSENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
